<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<div data-role="navbar">
	<ul>
		<li><a href="#" onclick="gofarmtwtSearch(FarmID)" data-theme="c">양식장</a></li>
		<li><a href="#" onclick="goButtonwtRec(FarmID)" data-theme="c">상태기록</a></li>
		<li><a href="#" onclick="goButtonwtUpdateForm(FarmID)" data-theme="c">조치기록</a></li>
		<li><a href="#" onclick="goButtonGrowInfoForm(FarmID)" data-theme="c">양식정보관련</a></li>
	</ul>
</div>

